# Your personal GitHub token
github_token: <your-personal-github-token>
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

timezone: Europe/London

box_check_update: false

machine_name: yii2basic

ip: 192.168.83.137

cpus: 1

memory: 1024
